# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
