# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_post_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
